run:
  timeout: 5m
  tests: true

linters:
  enable:
    - staticcheck
    - gocritic
    - gofumpt
    - gosec
    - ineffassign
    - errcheck
    - govet
    - unconvert
    - prealloc
    - misspell

linters-settings:
  gocritic:
    enabled-checks:
      # Default checks
      - appendAssign
      - argOrder
      - assignOp
      - badCall
      - badCond
      - badLock  # Detects suspicious mutex lock/unlock operations
      - captLocal
      - caseOrder
      - codegenComment
      - commentFormatting
      - defaultCaseOrder
      - deferInLoop  # Detects defer in loops (important for mutex operations)
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - elseif
      - exitAfterDefer
      - exposedSyncMutex  # Detects exposed mutex methods
      - flagDeref
      - flagName
      - ifElseChain
      - mapKey
      - newDeref
      - offBy1
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - sloppyTypeAssert
      - switchTrue
      - typeSwitchVar
      - underef
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc

  staticcheck:
    # SA2001: Empty critical section
    # SA2003: Deferred Lock right after locking (should be Unlock)
    # These are enabled by default in staticcheck
    checks: ["all"]

  gofumpt:
    extra-rules: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec