// Code generated by funcschema. DO NOT EDIT.

package fstools

import (
	"context"
	"encoding/json"

	"github.com/bpowers/go-agent/chat"
)

// readDirResult is the internal result wrapper that adds error handling
type readDirResult struct {
	ReadDirResult

	Error *string `json:"error,omitzero"`
}

// readDirTool implements chat.Tool for the ReadDir function
type readDirTool struct{}

func (readDirTool) MCPJsonSchema() string {
	return `{"name":"ReadDir","description":"Reads a directory from the test filesystem","inputSchema":{"type":"object","properties":{"path":{"type":"string","description":"Directory path to read (defaults to \".\" for root)"}},"additionalProperties":false},"outputSchema":{"type":"object","properties":{"error":{"type":["string","null"]},"files":{"type":"array","items":{"type":"object","properties":{"isDir":{"type":"boolean"},"name":{"type":"string"},"size":{"type":"integer"}},"required":["name","isDir","size"],"additionalProperties":false}}},"required":["files","error"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}}`
}

func (readDirTool) Name() string {
	return "ReadDir"
}

func (readDirTool) Description() string {
	return "Reads a directory from the test filesystem"
}

func (readDirTool) Call(ctx context.Context, input string) string {
	// Parse the input JSON
	var req ReadDirRequest
	if err := json.Unmarshal([]byte(input), &req); err != nil {
		errStr := "failed to parse input: " + err.Error()
		errResp := readDirResult{Error: &errStr}
		respBytes, _ := json.Marshal(errResp)
		return string(respBytes)
	}

	// Call the actual function
	result, err := ReadDir(ctx, req)

	// Wrap result with error handling
	wrapped := readDirResult{ReadDirResult: result}
	if err != nil {
		errStr := err.Error()
		wrapped.Error = &errStr
	}

	// Marshal the response
	respBytes, marshalErr := json.Marshal(wrapped)
	if marshalErr != nil {
		errStr := "failed to marshal response: " + marshalErr.Error()
		errResp := readDirResult{Error: &errStr}
		respBytes, _ := json.Marshal(errResp)
		return string(respBytes)
	}

	return string(respBytes)
}

// ReadDirTool is the tool definition for the ReadDir function
var ReadDirTool chat.Tool = readDirTool{}
