// Code generated by funcschema. DO NOT EDIT.

package fstools

import (
	"context"
	"encoding/json"

	"github.com/bpowers/go-agent/chat"
)

// readFileResult is the internal result wrapper that adds error handling
type readFileResult struct {
	ReadFileResult
	Error *string `json:"error,omitzero"`
}

// readFileTool implements chat.Tool for the ReadFile function
type readFileTool struct{}

func (readFileTool) MCPJsonSchema() string {
	return `{"name":"read_file","description":"Reads a file from the test filesystem","inputSchema":{"type":"object","properties":{"fileName":{"type":"string"}},"required":["fileName"],"additionalProperties":false},"outputSchema":{"type":"object","properties":{"content":{"type":"string"},"error":{"type":["string","null"]}},"required":["content","error"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}}`
}

func (readFileTool) Name() string {
	return "read_file"
}

func (readFileTool) Description() string {
	return "Reads a file from the test filesystem"
}

func (readFileTool) Call(ctx context.Context, input string) string {
	// Parse the input JSON
	var req ReadFileRequest
	if err := json.Unmarshal([]byte(input), &req); err != nil {
		errStr := "failed to parse input: " + err.Error()
		errResp := readFileResult{Error: &errStr}
		respBytes, _ := json.Marshal(errResp)
		return string(respBytes)
	}

	// Call the actual function
	result, err := ReadFile(ctx, req)

	// Wrap result with error handling
	wrapped := readFileResult{ReadFileResult: result}
	if err != nil {
		errStr := err.Error()
		wrapped.Error = &errStr
	}

	// Marshal the response
	respBytes, marshalErr := json.Marshal(wrapped)
	if marshalErr != nil {
		errStr := "failed to marshal response: " + marshalErr.Error()
		errResp := readFileResult{Error: &errStr}
		respBytes, _ := json.Marshal(errResp)
		return string(respBytes)
	}

	return string(respBytes)
}

// ReadFileTool is the tool definition for the ReadFile function
var ReadFileTool chat.Tool = readFileTool{}
