// Code generated by funcschema. DO NOT EDIT.

package fstools

import (
	"context"
	"encoding/json"

	"github.com/bpowers/go-agent/chat"
)

// writeFileResult is the internal result wrapper that adds error handling
type writeFileResult struct {
	WriteFileResult

	Error *string `json:"error,omitzero"`
}

// writeFileTool implements chat.Tool for the WriteFile function
type writeFileTool struct{}

func (writeFileTool) MCPJsonSchema() string {
	return `{"name":"WriteFile","description":"Writes a file to the test filesystem","inputSchema":{"type":"object","properties":{"content":{"type":"string"},"fileName":{"type":"string"}},"required":["fileName","content"],"additionalProperties":false},"outputSchema":{"type":"object","properties":{"error":{"type":["string","null"]},"success":{"type":"boolean"}},"required":["success","error"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}}`
}

func (writeFileTool) Name() string {
	return "WriteFile"
}

func (writeFileTool) Description() string {
	return "Writes a file to the test filesystem"
}

func (writeFileTool) Call(ctx context.Context, input string) string {
	// Parse the input JSON
	var req WriteFileRequest
	if err := json.Unmarshal([]byte(input), &req); err != nil {
		errStr := "failed to parse input: " + err.Error()
		errResp := writeFileResult{Error: &errStr}
		respBytes, _ := json.Marshal(errResp)
		return string(respBytes)
	}

	// Call the actual function
	result, err := WriteFile(ctx, req)

	// Wrap result with error handling
	wrapped := writeFileResult{WriteFileResult: result}
	if err != nil {
		errStr := err.Error()
		wrapped.Error = &errStr
	}

	// Marshal the response
	respBytes, marshalErr := json.Marshal(wrapped)
	if marshalErr != nil {
		errStr := "failed to marshal response: " + marshalErr.Error()
		errResp := writeFileResult{Error: &errStr}
		respBytes, _ := json.Marshal(errResp)
		return string(respBytes)
	}

	return string(respBytes)
}

// WriteFileTool is the tool definition for the WriteFile function
var WriteFileTool chat.Tool = writeFileTool{}
